apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/productcatalogservice:2
        ports:
        - containerPort: 80

