apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: jenkins
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP